services:
  app:
    build: .
    env_file:
      - .env.development
    ports:
      - 3000:3000
  redis:
    image: redis:7.2.4-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  redis_data:
    external: false
