services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  app:
    container_name: dotted
    build: .
    develop:
      watch:
        - path: .
          action: sync
          target: /app
          ignore:
            - node_modules/
        - path: package.json
          action: rebuild
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
      - REDIS_HOST=redis
      - GOOGLE_GEMINI_AI_KEY=$GOOGLE_GEMINI_AI_KEY
    ports:
      - 3000:${PORT:-3000}
    depends_on:
      - redis
    stop_signal: SIGINT
    command: bun dev

volumes:
  redis:
    name: "dotted-redis"
    external: false