services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ollama --version || exit 1
      interval: 10s
      timeout: 30s
      retries: 5

  app:
    container_name: dotted
    build: .
    develop:
      watch:
        - path: .
          action: sync
          target: /app
          ignore:
            - node_modules/
        - path: package.json
          action: rebuild
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - SUPABASE_PROJECT_ID=$SUPABASE_PROJECT_ID
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_SECRET=$SUPABASE_SECRET
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_HOST=ollama:11434
      - REDIS_HOST=redis
      - DOTTED_CREW_URL=${DOTTED_CREW_URL}
    ports:
      - 3000:${PORT:-3000}
    depends_on:
      - redis
      - ollama
    stop_signal: SIGINT
    command: bun dev

volumes:
  ollama:
    name: "dotted-ollama"
    external: false
  redis:
    name: "dotted-redis"
    external: false