services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - 6379:6379

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama

  app:
    container_name: dotted
    build: .
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - SUPABASE_PROJECT_ID=$SUPABASE_PROJECT_ID
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_SECRET=$SUPABASE_SECRET
      - OLLAMA_HOST=ollama:11434
      - REDIS_HOST=redis
    ports:
      - 3000:${PORT:-3000}
    depends_on:
      - redis
      - ollama

volumes:
  ollama: