create type "public"."media_type" as enum ('image', 'video');

drop policy "Enable read access for all users" on "public"."budget";

drop policy "Enable read access for all users" on "public"."schedules";

revoke delete on table "public"."budget" from "anon";

revoke insert on table "public"."budget" from "anon";

revoke references on table "public"."budget" from "anon";

revoke select on table "public"."budget" from "anon";

revoke trigger on table "public"."budget" from "anon";

revoke truncate on table "public"."budget" from "anon";

revoke update on table "public"."budget" from "anon";

revoke delete on table "public"."budget" from "authenticated";

revoke insert on table "public"."budget" from "authenticated";

revoke references on table "public"."budget" from "authenticated";

revoke select on table "public"."budget" from "authenticated";

revoke trigger on table "public"."budget" from "authenticated";

revoke truncate on table "public"."budget" from "authenticated";

revoke update on table "public"."budget" from "authenticated";

revoke delete on table "public"."budget" from "service_role";

revoke insert on table "public"."budget" from "service_role";

revoke references on table "public"."budget" from "service_role";

revoke select on table "public"."budget" from "service_role";

revoke trigger on table "public"."budget" from "service_role";

revoke truncate on table "public"."budget" from "service_role";

revoke update on table "public"."budget" from "service_role";

revoke delete on table "public"."schedules" from "anon";

revoke insert on table "public"."schedules" from "anon";

revoke references on table "public"."schedules" from "anon";

revoke select on table "public"."schedules" from "anon";

revoke trigger on table "public"."schedules" from "anon";

revoke truncate on table "public"."schedules" from "anon";

revoke update on table "public"."schedules" from "anon";

revoke delete on table "public"."schedules" from "authenticated";

revoke insert on table "public"."schedules" from "authenticated";

revoke references on table "public"."schedules" from "authenticated";

revoke select on table "public"."schedules" from "authenticated";

revoke trigger on table "public"."schedules" from "authenticated";

revoke truncate on table "public"."schedules" from "authenticated";

revoke update on table "public"."schedules" from "authenticated";

revoke delete on table "public"."schedules" from "service_role";

revoke insert on table "public"."schedules" from "service_role";

revoke references on table "public"."schedules" from "service_role";

revoke select on table "public"."schedules" from "service_role";

revoke trigger on table "public"."schedules" from "service_role";

revoke truncate on table "public"."schedules" from "service_role";

revoke update on table "public"."schedules" from "service_role";

alter table "public"."schedule_items" drop constraint "schedule_items_location_id_fkey";

alter table "public"."schedule_items" drop constraint "schedule_items_schedule_id_fkey";

alter table "public"."schedules" drop constraint "schedules_itinerary_id_fkey";

alter table "public"."budget" drop constraint "budget_pkey";

alter table "public"."schedules" drop constraint "schedules_pkey";

drop index if exists "public"."budget_pkey";

drop index if exists "public"."schedules_pkey";

drop table "public"."budget";

drop table "public"."schedules";

create table "public"."point_of_interests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text not null,
    "location_id" bigint not null,
    "address_id" bigint not null
);


alter table "public"."point_of_interests" enable row level security;

create table "public"."point_of_interests_media" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "point_of_interest_id" bigint not null,
    "media_id" bigint not null
);


alter table "public"."point_of_interests_media" enable row level security;

alter table "public"."itineraries" drop column "end_time";

alter table "public"."itineraries" drop column "start_time";

alter table "public"."itineraries" alter column "budget" set data type numeric using "budget"::numeric;

alter table "public"."itineraries" alter column "destination" set data type text using "destination"::text;

alter table "public"."itineraries" alter column "end_date" set data type timestamp without time zone using "end_date"::timestamp without time zone;

alter table "public"."itineraries" alter column "start_date" set data type timestamp without time zone using "start_date"::timestamp without time zone;

alter table "public"."media" add column "media_type" media_type not null;

alter table "public"."media" alter column "url" set data type text using "url"::text;

alter table "public"."schedule_items" drop column "description";

alter table "public"."schedule_items" drop column "location_id";

alter table "public"."schedule_items" drop column "name";

alter table "public"."schedule_items" drop column "schedule_id";

alter table "public"."schedule_items" add column "itinerary_id" bigint not null;

alter table "public"."schedule_items" add column "point_of_interest_id" bigint not null;

alter table "public"."schedule_items" alter column "end_time" set data type timestamp without time zone using "end_time"::timestamp without time zone;

alter table "public"."schedule_items" alter column "start_time" set data type timestamp without time zone using "start_time"::timestamp without time zone;

drop type "public"."budget_type";

drop type "public"."schedule_intensity";

drop type "public"."schedule_length";

CREATE UNIQUE INDEX media_url_key ON public.media USING btree (url);

CREATE UNIQUE INDEX poi_media ON public.point_of_interests_media USING btree (point_of_interest_id, media_id);

CREATE UNIQUE INDEX point_of_interests_pkey ON public.point_of_interests USING btree (id);

CREATE UNIQUE INDEX schedule_item_media_pkey ON public.point_of_interests_media USING btree (id);

alter table "public"."point_of_interests" add constraint "point_of_interests_pkey" PRIMARY KEY using index "point_of_interests_pkey";

alter table "public"."point_of_interests_media" add constraint "schedule_item_media_pkey" PRIMARY KEY using index "schedule_item_media_pkey";

alter table "public"."media" add constraint "media_url_key" UNIQUE using index "media_url_key";

alter table "public"."point_of_interests" add constraint "public_point_of_interests_address_id_fkey" FOREIGN KEY (address_id) REFERENCES addresses(id) not valid;

alter table "public"."point_of_interests" validate constraint "public_point_of_interests_address_id_fkey";

alter table "public"."point_of_interests" add constraint "public_point_of_interests_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id) not valid;

alter table "public"."point_of_interests" validate constraint "public_point_of_interests_location_id_fkey";

alter table "public"."point_of_interests_media" add constraint "poi_media" UNIQUE using index "poi_media";

alter table "public"."point_of_interests_media" add constraint "public_point_of_interests_media_point_of_interest_id_fkey" FOREIGN KEY (point_of_interest_id) REFERENCES point_of_interests(id) not valid;

alter table "public"."point_of_interests_media" validate constraint "public_point_of_interests_media_point_of_interest_id_fkey";

alter table "public"."point_of_interests_media" add constraint "public_schedule_item_media_media_id_fkey" FOREIGN KEY (media_id) REFERENCES media(id) not valid;

alter table "public"."point_of_interests_media" validate constraint "public_schedule_item_media_media_id_fkey";

alter table "public"."schedule_items" add constraint "public_schedule_items_itinerary_id_fkey" FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) not valid;

alter table "public"."schedule_items" validate constraint "public_schedule_items_itinerary_id_fkey";

alter table "public"."schedule_items" add constraint "public_schedule_items_point_of_interest_id_fkey" FOREIGN KEY (point_of_interest_id) REFERENCES point_of_interests(id) not valid;

alter table "public"."schedule_items" validate constraint "public_schedule_items_point_of_interest_id_fkey";

grant delete on table "public"."point_of_interests" to "anon";

grant insert on table "public"."point_of_interests" to "anon";

grant references on table "public"."point_of_interests" to "anon";

grant select on table "public"."point_of_interests" to "anon";

grant trigger on table "public"."point_of_interests" to "anon";

grant truncate on table "public"."point_of_interests" to "anon";

grant update on table "public"."point_of_interests" to "anon";

grant delete on table "public"."point_of_interests" to "authenticated";

grant insert on table "public"."point_of_interests" to "authenticated";

grant references on table "public"."point_of_interests" to "authenticated";

grant select on table "public"."point_of_interests" to "authenticated";

grant trigger on table "public"."point_of_interests" to "authenticated";

grant truncate on table "public"."point_of_interests" to "authenticated";

grant update on table "public"."point_of_interests" to "authenticated";

grant delete on table "public"."point_of_interests" to "service_role";

grant insert on table "public"."point_of_interests" to "service_role";

grant references on table "public"."point_of_interests" to "service_role";

grant select on table "public"."point_of_interests" to "service_role";

grant trigger on table "public"."point_of_interests" to "service_role";

grant truncate on table "public"."point_of_interests" to "service_role";

grant update on table "public"."point_of_interests" to "service_role";

grant delete on table "public"."point_of_interests_media" to "anon";

grant insert on table "public"."point_of_interests_media" to "anon";

grant references on table "public"."point_of_interests_media" to "anon";

grant select on table "public"."point_of_interests_media" to "anon";

grant trigger on table "public"."point_of_interests_media" to "anon";

grant truncate on table "public"."point_of_interests_media" to "anon";

grant update on table "public"."point_of_interests_media" to "anon";

grant delete on table "public"."point_of_interests_media" to "authenticated";

grant insert on table "public"."point_of_interests_media" to "authenticated";

grant references on table "public"."point_of_interests_media" to "authenticated";

grant select on table "public"."point_of_interests_media" to "authenticated";

grant trigger on table "public"."point_of_interests_media" to "authenticated";

grant truncate on table "public"."point_of_interests_media" to "authenticated";

grant update on table "public"."point_of_interests_media" to "authenticated";

grant delete on table "public"."point_of_interests_media" to "service_role";

grant insert on table "public"."point_of_interests_media" to "service_role";

grant references on table "public"."point_of_interests_media" to "service_role";

grant select on table "public"."point_of_interests_media" to "service_role";

grant trigger on table "public"."point_of_interests_media" to "service_role";

grant truncate on table "public"."point_of_interests_media" to "service_role";

grant update on table "public"."point_of_interests_media" to "service_role";

create policy "Enable read access for all users"
on "public"."addresses"
as permissive
for select
to authenticated
using (true);


create policy "Enable read access for all users"
on "public"."locations"
as permissive
for select
to authenticated
using (true);


create policy "Enable read access for all users"
on "public"."point_of_interests"
as permissive
for select
to authenticated
using (true);


create policy "Enable read access for all users"
on "public"."point_of_interests_media"
as permissive
for select
to authenticated
using (true);



