revoke delete on table "public"."destinations" from "anon";

revoke insert on table "public"."destinations" from "anon";

revoke references on table "public"."destinations" from "anon";

revoke select on table "public"."destinations" from "anon";

revoke trigger on table "public"."destinations" from "anon";

revoke truncate on table "public"."destinations" from "anon";

revoke update on table "public"."destinations" from "anon";

revoke delete on table "public"."destinations" from "authenticated";

revoke insert on table "public"."destinations" from "authenticated";

revoke references on table "public"."destinations" from "authenticated";

revoke select on table "public"."destinations" from "authenticated";

revoke trigger on table "public"."destinations" from "authenticated";

revoke truncate on table "public"."destinations" from "authenticated";

revoke update on table "public"."destinations" from "authenticated";

revoke delete on table "public"."destinations" from "service_role";

revoke insert on table "public"."destinations" from "service_role";

revoke references on table "public"."destinations" from "service_role";

revoke select on table "public"."destinations" from "service_role";

revoke trigger on table "public"."destinations" from "service_role";

revoke truncate on table "public"."destinations" from "service_role";

revoke update on table "public"."destinations" from "service_role";

alter table "public"."destinations" drop constraint "destinations_pkey";

drop index if exists "public"."destinations_pkey";

drop table "public"."destinations";

create table "public"."locations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "lat" numeric not null,
    "lon" numeric not null,
    "parent_id" bigint
);


alter table "public"."locations" enable row level security;

alter table "public"."addresses" add column "location_id" bigint not null;

alter table "public"."itineraries" add column "accommodation" text not null;

CREATE UNIQUE INDEX locations_pkey ON public.locations USING btree (id);

alter table "public"."locations" add constraint "locations_pkey" PRIMARY KEY using index "locations_pkey";

alter table "public"."addresses" add constraint "addresses_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."addresses" validate constraint "addresses_location_id_fkey";

grant delete on table "public"."locations" to "anon";

grant insert on table "public"."locations" to "anon";

grant references on table "public"."locations" to "anon";

grant select on table "public"."locations" to "anon";

grant trigger on table "public"."locations" to "anon";

grant truncate on table "public"."locations" to "anon";

grant update on table "public"."locations" to "anon";

grant delete on table "public"."locations" to "authenticated";

grant insert on table "public"."locations" to "authenticated";

grant references on table "public"."locations" to "authenticated";

grant select on table "public"."locations" to "authenticated";

grant trigger on table "public"."locations" to "authenticated";

grant truncate on table "public"."locations" to "authenticated";

grant update on table "public"."locations" to "authenticated";

grant delete on table "public"."locations" to "service_role";

grant insert on table "public"."locations" to "service_role";

grant references on table "public"."locations" to "service_role";

grant select on table "public"."locations" to "service_role";

grant trigger on table "public"."locations" to "service_role";

grant truncate on table "public"."locations" to "service_role";

grant update on table "public"."locations" to "service_role";


